version: "3.4"

services:
  api:
    image: ghcr.io/amodeus-app/amodeus-api
    restart: unless-stopped
    cap_drop:
      - ALL
    ports:
      - "${PORT:-8000}:8000"
    secrets:
      - source: config
        target: /app/config.yaml

secrets:
  config:
    file: ./config.yaml
